spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/store
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/catalogue
    username: catalogue
    password: catalogue
  flyway:
    schemas:
      - public
      - catalogue

server:
  port: 8081
logging:
  level:
    sql: info
